# FastAPI is the web framework
from fastapi import Depends

# SQLAlchemy imports for querying the database
from fastapi.routing import APIRouter
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.db.session import get_db
from app.models.user import User
from app.schemas.user import UserCreate, UserPublic

# ---------------------------------------------------------------------
# FASTAPI router.ICATION INSTANCE
# ---------------------------------------------------------------------
# We pass the lifespan function to FastAPI.
# FastAPI will call it automatically.
#

router = APIRouter(prefix="/users", tags=["users"])


# ---------------------------------------------------------------------
# ROUTES / ENDPOINTS
# ---------------------------------------------------------------------
#
@router.get("/users", response_model=list[UserPublic])
async def list_users(db: AsyncSession = Depends(get_db)):
    """
    GET /users

    Important concepts here:

    - `db` is an AsyncSession (NOT a TCP connection!)
    - The session BORROWS a TCP connection from the pool
      ONLY when it needs to execute SQL.
    - After the request finishes, the connection is returned to the pool.
    """

    # Build a SQL query: SELECT * FROM users;
    stmt = select(User)

    # Execute the query using a pooled TCP connection
    result = await db.execute(stmt)

    # Extract ORM objects from the result
    users = result.scalars().all()

    return list(users)


@router.post("/users", response_model=UserPublic)
async def create_user(payload: UserCreate, db: AsyncSession = Depends(get_db)):
    """
    POST /users

    Flow:
    1. Receive JSON from client
    2. Validate it with Pydantic (UserCreate)
    3. Create ORM object
    4. Commit transaction
    """

    # Convert validated input into ORM object
    user = User(**payload.model_dump())

    # Stage object for INSERT
    db.add(user)

    # Commit:
    # - opens a DB transaction
    # - uses a TCP connection from the pool
    # - writes data to PostgreSQL
    await db.commit()

    # Refresh:
    # - reloads data from DB
    # - needed to get autogenerated fields (e.g. id)
    await db.refresh(user)

    return user
